name: Git Checkout Workflow

on: push

jobs:
    first_job:
            runs-on : ubuntu-latest
            steps:
            - name: Checkout Repo
              uses: actions/checkout@v5    
            - name: Welcome Message
              run: | 
                echo "Ny First Github Actions Job"
                ls -ltra
                cat custom.txt
            - name: Generate ASCII artwork
              run: cowsay -f dragon "Run for cover, I am DRAGON ...." >> dragon.txt
        
                